# ai_service-repo/.github/workflows/release.yml

name: Create and Publish AI Service Docker Image

on:
  workflow_dispatch: # Permite acionamento manual pela interface do GitHub Actions

jobs:
  build_and_push_ai_service:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push AI Service image
        uses: docker/build-push-action@v5
        with:
          context: . # O contexto é a raiz do repositório atual
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/zapsign-ai-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ai-service-release-${{ github.run_number }}
          body: |
            New release for the AI Service.
            - Docker Image: `ghcr.io/${{ github.repository_owner }}/zapsign-ai-service:latest`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}